### ISSUE TITLE
你好，你用的opencv 哪个版本的呢

### ISSUE THREAD

**Issue by duoduo1018** [zhanglaplace/faster-rcnn-cplusplus2#1]
我的提示错误	180	error C2039: “Affine3”: 不是“cv”的成员 (..\..\examples\cpp_faster_rcnn\demo.cpp)	...\OpenCV.2.4.10\build\native\include\opencv2\core\affine.hpp
谢谢你的分享

**Comment by zhanglaplace** [comment]
2.4.9
